---
- name: Check if Monitoring token is defined
  fail:
    msg: "monitoring_token is mandatory"
  when: monitoring_token is undefined

- name: Check if Infra token is defined
  fail:
    msg: "infra_token is mandatory"
  when: infra_token is undefined

- name: Check if App type is defined
  fail:
    msg: "app_type is mandatory"
  when: app_type is undefined

- name: Initialise extra arguments
  set_fact:
    extra_args: ""

- name: Check if App subtype is defined
  set_fact:
    extra_args: "{{ extra_args }} --app-subtype {{ app_subtype }}"
  when: app_subtype is defined

- name: Prepare specific arguments
  set_fact:
    extra_args: "{{ extra_args }} --{{ item.key }} {{ item.value }}"
  with_dict: "{{ agent_args }}"
  when: agent_args is defined

- name: Configure monitor without App subtype
  command: >
      /opt/spm/bin/setup-sematext
      --monitoring-token {{ monitoring_token }}
      --infra-token {{ infra_token }}
      --agent-type {{ agent_type }}
      --app-type {{ app_type }}
      {{ extra_args }}
  args:
    creates: "/opt/spm/spm-monitor/conf/spm-monitor-config-\
      {{ monitoring_token }}-{{ app_name }}.properties"
  when: app_subtype is not defined

- name: Configure monitor with App subtype
  command: >
      /opt/spm/bin/setup-sematext
      --monitoring-token {{ monitoring_token }}
      --infra-token {{ infra_token }}
      --agent-type {{ agent_type }}
      --app-type {{ app_type }}
      {{ extra_args }}
  args:
    creates: "/opt/spm/spm-monitor/conf/spm-monitor-\
      {{ app_subtype }}-config-{{ monitoring_token }}-{{ app_name }}.properties"
  when: app_subtype is defined
