---
- name: Setup monitor without JVM name
  command: bash /opt/spm/bin/spm-client-setup-conf.sh {{ spm_token }} {{ java_app_type }} {{ spm_type }} jvmname:{{ java_jvm_name }}
  when: java_app_subtype is not defined

- name: Setup monitor without JVM name
  command: bash /opt/spm/bin/spm-client-setup-conf.sh {{ spm_token }} {{ java_app_type }} {{ spm_type }} {{ java_app_subtype }} jvmname:{{ java_jvm_name }}
  when: java_app_subtype is defined

- name: Setup tracing
  replace:
    dest: /opt/spm/spm-monitor/conf/spm-monitor-config-{{ spm_token }}-{{ java_jvm_name }}.properties
    regexp: '^(SPM_MONITOR_TRACING_ENABLED=).*'
    replace: '\1{{ tracing }}'
  when: tracing is defined and java_app_subtype is not defined

- name: Setup tracing
  replace:
    dest: /opt/spm/spm-monitor/conf/spm-monitor-{{ java_app_subtype }}-config-{{ spm_token }}-{{ java_jvm_name }}.properties
    regexp: '^(SPM_MONITOR_TRACING_ENABLED=).*'
    replace: '\1{{ tracing }}'
  when: tracing is defined and java_app_subtype is defined

- name: Setup JMX
  replace:
    dest: /opt/spm/spm-monitor/conf/spm-monitor-config-{{ spm_token }}-{{ java_jvm_name }}.properties
    regexp: '^(SPM_MONITOR_JMX_PARAMS=).*'
    replace: '\1"{{ jmx_params }}"'
  when: jmx_params is defined and java_app_subtype is not defined

- name: Setup JMX
  replace:
    dest: /opt/spm/spm-monitor/conf/spm-monitor-{{ java_app_subtype }}-config-{{ spm_token }}-{{ java_jvm_name }}.properties
    regexp: '^(SPM_MONITOR_JMX_PARAMS=).*'
    replace: '\1"{{ jmx_params }}"'
  when: jmx_params is defined and java_app_subtype is defined
